### ISSUE TITLE
docs: update for simplified reana-client commands

### ISSUE THREAD

**Issue by dinosk** [reanahub/reana-demo-root6-roofit#21]

**Comment by diegodelemos** [comment]
Addressed by https://github.com/reanahub/reana-demo-root6-roofit/pull/23,  https://github.com/reanahub/reana-demo-root6-roofit/pull/24, https://github.com/reanahub/reana-demo-root6-roofit/pull/25.

**Comment by tiborsimko** [comment]
All completed.
